/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TermProject;

/**
 *
 * @author pc
 */
public class MenuPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    public MenuPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        AddMovie = new javax.swing.JButton();
        AddStar = new javax.swing.JButton();
        DisplayInfo = new javax.swing.JButton();
        DisplayImage = new javax.swing.JButton();
        ListMovie = new javax.swing.JButton();
        ShowMovies = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("MENU");

        AddMovie.setText("Add a Movie");
        AddMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddMovieActionPerformed(evt);
            }
        });

        AddStar.setText("Add a Star");
        AddStar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddStarActionPerformed(evt);
            }
        });

        DisplayInfo.setText("Display Info");
        DisplayInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayInfoActionPerformed(evt);
            }
        });

        DisplayImage.setText("Display Image");
        DisplayImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayImageActionPerformed(evt);
            }
        });

        ListMovie.setText("List Movies");
        ListMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListMovieActionPerformed(evt);
            }
        });

        ShowMovies.setText("Show Movies of a Star");
        ShowMovies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowMoviesActionPerformed(evt);
            }
        });

        ExitButton.setText("EXIT");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ListMovie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ShowMovies, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DisplayImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DisplayInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AddStar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AddMovie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(ExitButton)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(AddMovie)
                .addGap(20, 20, 20)
                .addComponent(AddStar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(DisplayInfo)
                .addGap(20, 20, 20)
                .addComponent(DisplayImage)
                .addGap(20, 20, 20)
                .addComponent(ListMovie)
                .addGap(20, 20, 20)
                .addComponent(ShowMovies)
                .addGap(18, 18, 18)
                .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddMovieActionPerformed
            AddMovie add=new AddMovie();
            add.setVisible(true);
            this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_AddMovieActionPerformed

    private void ShowMoviesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowMoviesActionPerformed
       ShowStars star=new ShowStars();
            star.setVisible(true);
            this.dispose(); 
    }//GEN-LAST:event_ShowMoviesActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
    System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void AddStarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddStarActionPerformed
            AddStar addStar=new AddStar();
            addStar.setVisible(true);
            this.dispose();   
    }//GEN-LAST:event_AddStarActionPerformed

    private void DisplayInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayInfoActionPerformed
        DisplayInfo info=new DisplayInfo();
            info.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_DisplayInfoActionPerformed

    private void DisplayImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayImageActionPerformed
        DisplayImage image=new DisplayImage();
            image.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_DisplayImageActionPerformed

    private void ListMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListMovieActionPerformed
       ShowRate show=new ShowRate();
            show.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_ListMovieActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddMovie;
    private javax.swing.JButton AddStar;
    private javax.swing.JButton DisplayImage;
    private javax.swing.JButton DisplayInfo;
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton ListMovie;
    private javax.swing.JButton ShowMovies;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
